#!/bin/bash
clear
vidLocation="$USER/Videos"
vidFile=""
vidSeek="0:00"
vidLength="10"
imgLocation="gifmake_export"
imgPrefix="png"
gifCrop="176+40"
gifRes="1000x500+"
gifDelay="8"
gifFuzz="1.6"
gifLoop="-loop 0"
gifName="Almost.gif"
Exit=0
until [ $Exit -eq 1 ]; do
echo "Easy Gif Make Menu"
echo " Choices:"
echo "         1)  select input folder and video"
echo "		2) set video seek, length, output folder"
echo "         3)  select image crop and type"
echo "		4) set animated settings"
echo "		5) create the gif"
echo "		6) compress the gif"
echo "		7) Exit"
read choice

case $choice in

1) 	echo "set video location folder"
	read vidLocation
	echo "set video"
	read vidFile
;;
2)	echo "set the video seek (0:00)"
	read vidSeek
	echo "set the gif length (seconds)"
	read vidLength
	echo "set gif output folder"
	read imgLocation
;;
3)	echo "set the frame image prefix"
	echo "		1) png"
	echo "		2) jpg"
	read imgType
	case $imgType in
	1) imgPrefix="png";;
	2) imgPrefix="jpg";;
	*)  echo "wrong choice" 
	esac
 	echo "set resolution:"
	echo "		1) 1000x500"
	echo "		2) 500 x 250"
	echo "		3) 400 x 200"
	read gifResMenu
	case $gifResMenu in
	1)	imgRes="1000x500+";;	
	2)	imgRes="500x250+";;
	3)	imgRes="400x200+";;
	*)  echo "wrong choice" ;;
	esac
	echo "set crop:"
	echo "		1) 50+ 10"
	echo "		2) 250 + 40"
	echo "		3) 0 + 0"
	echo "		4) 10 + 50"
	read gifCropMenu
	case $gifCropMenu in
	1)	imgCrop="50+10" ;;
	2)	imgCrop="250+40" ;;
	3)	imgCrop="0+0" ;;
	4)	imgCrop="10+50" ;;
	*) echo "wrong choice" ;;
	esac
;;
4)	echo "set the fuzz amount (1.6)"
	read fuzzMenu
	echo "set the animated speed (frame delay e.g. 8)"
	read gifDelay
	echo "loop forever? [y/n]"
	read gifLoop
	if [ $gifLoop == "y" ]
	 then
		Loop="-loop 0"
	else
		Loop=""
	fi
	echo "set the output gif name (no extension)"
	read gifName
;;
5)	# copy and convert
	mplayer -ss $vidSeek -endpos $vidLength $vidLocation/$vidFile -vo png:z=1:outdir=$imgLocation -ao null
	 convert -crop $imgRes$imgCrop +repage -fuzz $fuzzMenu -delay $gifDelay $Loop $imgLocation/*.$imgPrefix -layers OptimizeTransparency $gifName.gif
;;
# compress 
6) 	gifsicle -O3 --colors 256 $gifName.gif > complete.gif
;;
7)	Exit=1;;
*)  echo "wrong choice" ;;
esac
done
